[CmdletBinding()]
param(
    [string]$ModuleName = 'Capsulenv',
    [string]$SourcePath = (Join-Path $PSScriptRoot 'src'),
    [string]$ManifestPath = (Join-Path $PSScriptRoot 'Capsulenv.psd1'),
    [string]$OutputRoot = (Join-Path $PSScriptRoot '.build'),
    [switch]$Clean
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Write-Utf8BomFile {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Content
    )

    $encoding = New-Object System.Text.UTF8Encoding($true)
    [System.IO.File]::WriteAllText($Path, $Content, $encoding)
}

function Test-PowerShellSyntax {
    param([Parameter(Mandatory = $true)][string]$Path)

    $content = [System.IO.File]::ReadAllText($Path)
    $errors = $null
    $tokens = $null
    [void][System.Management.Automation.Language.Parser]::ParseInput(
        $content,
        [ref]$tokens,
        [ref]$errors
    )

    if ($errors -and $errors.Count -gt 0) {
        $details = foreach ($errorItem in $errors) {
            '{0}:{1}:{2}: {3}' -f (
                $Path,
                $errorItem.Extent.StartLineNumber,
                $errorItem.Extent.StartColumnNumber,
                $errorItem.Message
            )
        }
        throw "PowerShell syntax check failed:`n$($details -join [Environment]::NewLine)"
    }
}

function ConvertTo-ManifestList {
    param([string[]]$Names)

    $items = @($Names | Where-Object { $_ } | Sort-Object -Unique)
    if ($items.Count -eq 0) {
        return ''
    }

    return (($items | ForEach-Object { "'$_'" }) -join ",`r`n        ")
}

if (-not (Test-Path -LiteralPath $SourcePath -PathType Container)) {
    throw "Module source directory does not exist: $SourcePath"
}
if (-not (Test-Path -LiteralPath $ManifestPath -PathType Leaf)) {
    throw "Module manifest does not exist: $ManifestPath"
}

$outputPath = Join-Path $OutputRoot $ModuleName
if ($Clean -and (Test-Path -LiteralPath $outputPath)) {
    Remove-Item -LiteralPath $outputPath -Recurse -Force
}
[void](New-Item -ItemType Directory -Path $outputPath -Force)

$sourceFiles = @(
    Get-ChildItem -LiteralPath $SourcePath -Filter '*.ps1' -File -Recurse |
        Sort-Object FullName
)
if ($sourceFiles.Count -eq 0) {
    throw "No PowerShell source files were found in: $SourcePath"
}

$functionsToExport = New-Object System.Collections.Generic.List[string]
$aliasesToExport = New-Object System.Collections.Generic.List[string]
$chunks = New-Object System.Collections.Generic.List[string]
$chunks.Add("# Generated by Merge-ModuleScripts.ps1. Do not edit this file directly.`r`n")

foreach ($file in $sourceFiles) {
    Test-PowerShellSyntax -Path $file.FullName
    $content = [System.IO.File]::ReadAllText($file.FullName)

    $functionMatches = [regex]::Matches(
        $content,
        '(?m)^[ \t]*##MOD_EXEC##[ \t]+Export-ModuleMember[ \t]+-Function[ \t]+([-_A-Za-z0-9, \t]+)[ \t]*\r?$'
    )
    foreach ($match in $functionMatches) {
        foreach ($name in ($match.Groups[1].Value -split ',')) {
            $trimmed = $name.Trim()
            if ($trimmed) {
                $functionsToExport.Add($trimmed)
            }
        }
    }

    $aliasMatches = [regex]::Matches(
        $content,
        '(?m)^[ \t]*##MOD_EXEC##[ \t]+Export-ModuleMember[ \t]+-Alias[ \t]+([-_A-Za-z0-9, \t]+)[ \t]*\r?$'
    )
    foreach ($match in $aliasMatches) {
        foreach ($name in ($match.Groups[1].Value -split ',')) {
            $trimmed = $name.Trim()
            if ($trimmed) {
                $aliasesToExport.Add($trimmed)
            }
        }
    }

    $cleanContent = [regex]::Replace(
        $content,
        '(?m)^[ \t]*##MOD_EXEC##[ \t]+Export-ModuleMember[ \t]+-(Function|Alias)[ \t]+[-_A-Za-z0-9, \t]+[ \t]*\r?\n?',
        ''
    )
    $relativeName = $file.FullName.Substring($SourcePath.TrimEnd('\', '/').Length).TrimStart('\', '/')
    $chunks.Add("`r`n# region $relativeName`r`n$cleanContent`r`n# endregion $relativeName`r`n")
}

$uniqueFunctions = @($functionsToExport | Sort-Object -Unique)
$uniqueAliases = @($aliasesToExport | Sort-Object -Unique)

if ($uniqueFunctions.Count -gt 0 -or $uniqueAliases.Count -gt 0) {
    $exportLines = New-Object System.Collections.Generic.List[string]
    $exportLines.Add('Export-ModuleMember `')
    if ($uniqueFunctions.Count -gt 0) {
        $quotedFunctions = ($uniqueFunctions | ForEach-Object { "'$_'" }) -join ', '
        $suffix = if ($uniqueAliases.Count -gt 0) { ' `' } else { '' }
        $exportLines.Add("    -Function $quotedFunctions$suffix")
    }
    if ($uniqueAliases.Count -gt 0) {
        $quotedAliases = ($uniqueAliases | ForEach-Object { "'$_'" }) -join ', '
        $exportLines.Add("    -Alias $quotedAliases")
    }
    $chunks.Add("`r`n$($exportLines -join "`r`n")`r`n")
}

$psm1Path = Join-Path $outputPath "$ModuleName.psm1"
Write-Utf8BomFile -Path $psm1Path -Content ($chunks -join '')
Test-PowerShellSyntax -Path $psm1Path

$manifestText = [System.IO.File]::ReadAllText($ManifestPath)
$manifestText = $manifestText.Replace(
    "'__GENERATED_FUNCTIONS__'",
    (ConvertTo-ManifestList -Names $uniqueFunctions)
)
$manifestText = $manifestText.Replace(
    "'__GENERATED_ALIASES__'",
    (ConvertTo-ManifestList -Names $uniqueAliases)
)
$generatedManifestPath = Join-Path $outputPath "$ModuleName.psd1"
Write-Utf8BomFile -Path $generatedManifestPath -Content $manifestText
Test-PowerShellSyntax -Path $generatedManifestPath

Get-ChildItem -LiteralPath $SourcePath -File -Recurse |
    Where-Object { $_.Extension -ne '.ps1' } |
    ForEach-Object {
        $relativePath = $_.FullName.Substring($SourcePath.TrimEnd('\', '/').Length).TrimStart('\', '/')
        $destination = Join-Path $outputPath $relativePath
        [void](New-Item -ItemType Directory -Path (Split-Path -Parent $destination) -Force)
        Copy-Item -LiteralPath $_.FullName -Destination $destination -Force
    }

$manifest = Test-ModuleManifest -Path $generatedManifestPath -ErrorAction Stop
[pscustomobject]@{
    ModuleName = $manifest.Name
    ModuleVersion = $manifest.Version.ToString()
    ModulePath = $generatedManifestPath
    Functions = $uniqueFunctions
    Aliases = $uniqueAliases
}
